#--------------------------------------------------------
# Dockefile to build Docker Image of Nginx Server
#
#--------------------------------------------------------

FROM nginx:stable


CMD ["/usr/sbin/nginx", "-D","FOREGROUND"]
EXPOSE 8080